config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root 'welcome#index'

  resources :players

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?
      can :manage, :all
    else
      can :create, Player

      can :update, Player do |player|
        player.user == user
      end

      can :destroy, Player do |player|
        player.user == user
      end

    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_attached_file :image, styles: { large: "600x600", medium: "300x300", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_attached_file :transcript
  validates_attachment :transcript, content_type: { content_type: %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

  has_attached_file :sat_scores
  validates_attachment :sat_scores, content_type: { content_type: %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all.order("created_at DESC")
  end

  def show
  end

  def new
    @player = current_user.players.build
  end

  def create
    @player = current_user.players.build(player_params)

    if @player.save
      redirect_to @player
    else
      render 'form'
    end
  end

  def edit
  end

  def update
    if @player.update(player_params)
      redirect_to @player
    else
      render 'edit'
    end
  end

  def destroy
    @player.destroy
    redirect_to players_path
  end

  private
  def find_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :position, :school, :bio, :highlight, :image, :transcript, :sat_scores)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ALOSports
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand.page-scroll{:href => root_path} ALO Sports
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            -if user_signed_in?
              %li
                = link_to "About Us", root_path(:anchor => "about")
            - if user_signed_in?
              %li
                = link_to "Mission", root_path(:anchor => "mission")
            - if user_signed_in?
              %li
                = link_to "Combine Format", root_path(:anchor => "combine")
            - if user_signed_in?
              %li
                = link_to "Affiliates", root_path(:anchor => "affiliates")
            - if user_signed_in?
              %li
                = link_to "Players", players_path, class: "nav navbar-link"
              %li
                = link_to "New Player", new_player_path, class: "nav navbar-link"
              %li
                = link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav navbar-link"
            - else
              %li
                = link_to "Sign Up", new_user_registration_path, class: "nav navbar-link"
              %li
                = link_to "Sign In", new_user_session_path, class: "nav navbar-link"
        / /.navbar-collapse
      / /.container-fluid

    .container
      %p.notice= notice
      %p.alert= alert
    = yield

app/views/players/_form.html.haml
= simple_form_for @player, html: { multipart: true } do |f|
  = f.input :name, placeholder: 'Enter Full Name', input_html: { class: 'form-control' }
  = f.input :position, placeholder: 'Enter Position', input_html: { class: 'form-control' }
  = f.input :school, placeholder: 'Enter School', input_html: { class: 'form-control' }
  = f.input :bio, placeholder: 'Enter Bio', input_html: { class: 'form-control' }
  = f.input :highlight, placeholder: 'Enter Link to Highlight Video', input_html: { class: 'form-control' }
  = f.input :image, as: :file, input_html: { class: 'form-control' }
  = f.input :transcript, as: :file, input_html: { class: 'form-control' }
  = f.input :sat_scores, as: :file, input_html: { class: 'form-control' }

  %br
  = f.button :submit

app/views/players/edit.html.haml
%h1 Edit Your Player Info

= render 'form'

= link_to "Cancel", player_path

app/views/players/index.html.haml
- @players.each do |player|
  .container
    .row
      .col-lg-12
        %h2= link_to player.name, player
        = image_tag player.image.url(:thumb)

app/views/players/new.html.haml
.container
  .row
    %h1 Add A New Player

    = render 'form'
    %br
    = link_to "Cancel", root_path, { class: "btn btn-primary"}

app/views/players/show.html.haml
.container
  .row
    %h1.player_name= @player.name
    = image_tag @player.image.url(:medium)
    %h5
      Position: #{@player.position}
    %h5
      School: #{@player.school}
    %h5
      Highlight Video:
      = link_to @player.highlight, @player.highlight
    %h5 Bio:
    %p= @player.bio

  - if can? :update, @player
    = link_to "Transcript", @player.transcript.url(:original, false), { class: "btn btn-primary" }
    = link_to "SAT Scores", @player.sat_scores.url(:original, false), { class: "btn btn-primary" }
    = link_to "Edit", edit_player_path(@player), { class: "btn btn-primary btn-group" }
    = link_to "Delete", player_path(@player), class: "btn btn-primary", method: :delete, data: { confirm: "Are you sure?"}

  - else
    %br

    %br
    = link_to "All Players", players_path, { class: "btn btn-primary btn-group" }

app/views/welcome/index.html.haml
/ Intro Header
%header.intro
  .intro-body
    .container
      .row
        .col-md-8.col-md-offset-2
          %h1.brand-heading ALO Sports
          %p.intro-text
            We are a company that strives to make the college process easier for both players and coaches.
            %br>/
          %a.btn.btn-circle.page-scroll{:href => "#about"}
            %i.fa.fa-angle-double-down.animated
/ About Section
%section#about.container.content-section.text-center
  .row
    .col-lg-8.col-lg-offset-2
      %h2 About ALO Sports
      %p
        Grayscale is a free Bootstrap 3 theme created by Start Bootstrap. It can be yours right now, simply download the template on
        = succeed "." do
          %a{:href => "http://startbootstrap.com/template-overviews/grayscale/"} the preview page
      %p
        This theme features stock photos by
        %a{:href => "http://gratisography.com/"} Gratisography
        along with a custom Google Maps skin courtesy of
        = succeed "." do
          %a{:href => "http://snazzymaps.com/"} Snazzy Maps
      %p Grayscale includes full HTML, CSS, and custom JavaScript files along with LESS files for easy customization.
/ Mission Section
%section#mission.content-section.text-center
  .mission-section
    .container
      .col-lg-8.col-lg-offset-2
        %h2 The mission of ALO Sports is too...
        %p More text goes here.
        %a.btn.btn-default.btn-lg{:href => "#"} Sign Up
/ Combine Section
%section#combine.container.content-section.text-center
  .row
    .col-lg-8.col-lg-offset-2
      %h2 Combine Format
      %p Feel free to email us if you have any questions regarding the combine.

/ Affiliates Section
%section#affiliates.content-section.text-center
  .affiliates-section
    .container
      .col-lg-8.col-lg-offset-2
        %h2 Affiliates
        %p
          ALO Sports partners with some wonderful affiliates, if interested please take the time to check them out.
          %a{:href => "http:/www.aboveandbeyondhighlights.com"} Above &amp; Beyond Highlights

/ Footer
%footer
  .container.text-center
    %p Copyright &#169; ALO Sports